// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swcjqjqmaafmuajbfkai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3Y2pxanFtYWFmbXVhamJma2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTc4NzEsImV4cCI6MjA2NTYzMzg3MX0.Wu24T6qhSoRSJjCGyD7uv4kkpCtIUE6F5aKtcAiBcYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);